config/routes.rb
Performo::Application.routes.draw do

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/news', to: 'static_pages#news'

  root :to => "static_pages#home"

  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :performers do
    collection do
      get :search
    end

    resources :reviews
  end

end

app/models/performer.rb
class Performer < ActiveRecord::Base
  attr_accessible :description, :name

  validates :name, :presence => true
  validates :description, :presence => true,
                          :length => { :minimum => 5, :maximum => 140 }
  validates :user_id, presence: true

  has_many :reviews, :dependent => :destroy
  belongs_to :user, :inverse_of => :performers
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :performer
  attr_accessible :body, :reviewer
  validates :body, :presence => true
  validates :reviewer, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :performers, :dependent => :destroy, :inverse_of => :user

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, 
    :presence => true, 
    :length => { :maximum => 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 
    :presence => true, 
    :format => { :with => VALID_EMAIL_REGEX },
    :uniqueness => { :case_sensitive => false }
  validates :password,
    :presence => true,
    :length => { :minimum => 6}
  validates :password_confirmation,
    :presence => true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  # GET /performers
  # GET /performers.json
  before_filter :signed_in_user, except: [:index]
  #before_filter :correct_user, only: [:edit,:update, :delete]

  def index
    @performers = Performer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @performers }
    end
  end

  # GET /performers/1
  # GET /performers/1.json
  def show
    @performer = Performer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @performer }
    end
  end

  # GET /performers/new
  # GET /performers/new.json
  def new
    @performer = Performer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @performer }
    end
  end

  # GET /performers/1/edit
  def edit
    @performer = Performer.find(params[:id])
  end

  # POST /performers
  # POST /performers.json
  def create
    @performer = current_user.performers.build(params[:performer])

    respond_to do |format|
      if @performer.save
        format.html { redirect_to @performer, notice: 'Performer was successfully saved.' }
        format.json { head :no_content }
      else
        flash.now[:error] = "Unable to save performer"
        format.html { render action: "new" }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /performers/1
  # PUT /performers/1.json
  def update
    @performer = Performer.find(params[:id])

    respond_to do |format|
      if @performer.update_attributes(params[:performer])
        format.html { redirect_to @performer, notice: 'Performer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performers/1
  # DELETE /performers/1.json
  def destroy
    @performer = Performer.find(params[:id])
    @performer.destroy

    respond_to do |format|
      format.html { redirect_to performers_url }
      format.json { head :no_content }
    end
  end

  # FIXME: duplicate code (user_controller.rb duplicated)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @performer = Performer.find(params[:performer_id])
    @review = @performer.reviews.create(params[:review])
    redirect_to performer_path(@performer)
  end

  def destroy
    @performer = Performer.find(params[:performer_id])
    @review = @performer.reviews.find(params[:review])
    @review.destroy
    redirect_to performer_path(@performer)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @performers = @user.performers.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def edit 
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Performo!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
  private 

    def correct_user
      @user = User.find_by_id(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
  end

  def correct_user
    @user = User.find_by_id(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar", width:"109",height:"109")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<nav>
<ul>
  <li><%= link_to "About", about_path %></li>
  <li><%= link_to "Contact", contact_path %></li>
  <li><a href="http://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
  <div class="container">
    <%= link_to "Performo", root_path, class: "logo" %>
    <nav>
    <form class="form-search pull-left">
      <input type="text" class="input-medium search-query">
      <button type="submit" class="btn">Search</button>
    </form>
    <ul class="nav pull-right">
      <li><%= link_to "Sign Up",    signup_path %></li>
      <% if signed_in? %>
        <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
          <%= link_to "Sign out", signout_path, method: "delete" %>
          </li>
        </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    <li><%= link_to "Help",    help_path %></li>
    </ul>     
    <button class="btn btn-small btn-primary pull-right"><%= link_to "List your band", new_performer_path %>  <i class="icon-music icon-white"></i></button>
    </nav>
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Performo</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="main" role="main">
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key%>"><%= value %></div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>

app/views/performers/_form.html.erb
<%= form_for(@performer) do |f| %>
  <% if @performer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@performer.errors.count, "error") %> prohibited this performer from being saved:</h2>

      <ul>
      <% @performer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit :List %>
  </div>
<% end %>

app/views/performers/_performer.html.erb
<li>
  <span class="content"><%= performer.name %> <%= link_to "Edit listing", edit_performer_path(performer) %></span>
</li>

app/views/performers/edit.html.erb
<h1>Editing performer</h1>

<%= render 'form' %>

<%= link_to 'Show', @performer %> |
<%= link_to 'Back', performers_path %>

app/views/performers/index.html.erb
<h1>Listing performers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @performers.each do |performer| %>
  <tr>
    <td><%= performer.name %></td>
    <td><%= link_to 'Details', performer %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Performer', new_performer_path %>

app/views/performers/new.html.erb
<h1>List your performer!</h1>

<%= render 'form' %>

<%= link_to 'Back', performers_path %>

app/views/performers/show.html.erb
<title>View performer</title>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @performer.name %>
</p>

<p>
  <b>Description:</b>
  <%= @performer.description %>
</p>

<h2>Reviews</h2>
<%= render @performer.reviews %>

<br />

<%= link_to "Edit listing", edit_performer_path(@performer) %>

<%= link_to 'Back', performers_path %>

app/views/reviews/_form.html.erb
<%= form_for([@performer, @performer.reviews.build]) do |f| %>
  <div class="field">
    <%= f.label :reviewer %><br />
    <%= f.text_field :reviewer %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<p>
  <b>Reviewer:</b>
  <%= review.reviewer %>
</p>

<p>
  <b>Review:</b>
  <%= review.body %>
</p>

<p>
  <%= link_to 'Delete Review', [review.performer, review],
              :confirm => 'Are you sure?',
              :method => :delete %>
</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>ABOUTTTT</h1>

app/views/static_pages/contact.html.erb
<h1>CONTACTTT</h1>

app/views/static_pages/help.html.erb
<h1> HELPPPP</h1>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Performo</h1>
  <h2>Turn your backyard into a venue!</h2>
  <%= link_to "Browse Listed Bands!", performers_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/edit.html.erb
<title>Edit user</title>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account" %>
    <%end %>
  </div>
</div>

app/views/users/show.html.erb
<title><%= @user.name %></title>
<div class="container-fluid">
  <div class="row-fluid">
    <span class="span6">
      <section class="box">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <h4>
        <%= link_to "Edit profile", edit_user_path(@user) %>
      </h4>
      </section>
    </span>
    <span class="span6">
      <% if @user.performers.any? %>
        <section class="box">
        <h3>Listed Performers</h3>
        <ol class="performers">
          <%= render @performers %>
        </ol>
        <%= will_paginate @performers %>
      <% end %>
      </section>
    </span>
  </div>
</div>